@echo off
REM Quick setup script for AI conversations (Multi-AI Council)
REM For Windows CMD

echo ========================================
echo AI Conversation Script Setup
echo ========================================
echo.

REM Check if Python is available
python --version >nul 2>&1
if %errorlevel% neq 0 (
    echo ERROR: Python is not installed or not in PATH
    echo Please install Python 3.8+ from https://www.python.org/
    pause
    exit /b 1
)

echo [1/3] Installing required packages...
python -m pip install -q -r ai_conversation_requirements.txt
if %errorlevel% neq 0 (
    echo ERROR: Failed to install packages
    pause
    exit /b 1
)
echo [OK] Packages installed

echo.
echo [2/3] API Key Configuration
echo.
echo Configure API keys for multi-AI diversity (at least one required):
echo   - OpenAI (GPT-4):     https://platform.openai.com/api-keys
echo   - Google Gemini:      https://aistudio.google.com/app/apikey
echo   - Anthropic (Claude): https://console.anthropic.com/
echo.

set /p OPENAI_KEY="Enter OpenAI API key (or press Enter to skip): "
set /p GEMINI_KEY="Enter Gemini API key (or press Enter to skip): "
set /p ANTHROPIC_KEY="Enter Anthropic API key (or press Enter to skip): "

REM Check that at least one key was provided
if "%OPENAI_KEY%"=="" if "%GEMINI_KEY%"=="" if "%ANTHROPIC_KEY%"=="" (
    echo.
    echo WARNING: No API keys provided. You must configure at least one before running.
    echo Keys can be set later in the .env file.
    pause
    exit /b 1
)

REM Write keys to .env file for persistence
echo # AI Conversation API Keys > .env
echo # Generated by setup_ai_conversation.bat on %date% %time% >> .env
echo. >> .env

if not "%OPENAI_KEY%"=="" (
    echo OPENAI_API_KEY=%OPENAI_KEY% >> .env
    echo [OK] OpenAI key saved to .env
)

if not "%GEMINI_KEY%"=="" (
    echo GEMINI_API_KEY=%GEMINI_KEY% >> .env
    echo [OK] Gemini key saved to .env
)

if not "%ANTHROPIC_KEY%"=="" (
    echo ANTHROPIC_API_KEY=%ANTHROPIC_KEY% >> .env
    echo [OK] Anthropic key saved to .env
)

echo.
echo [3/3] Ready to run!
echo.
echo ========================================
echo Next Steps:
echo ========================================
echo 1. API keys saved to .env file (gitignored for security)
echo 2. Use knowledge base context: python ai_conversation.py --context ../knowledge-base/ip-context
echo 3. Or run via root wrapper: ..\..\run_agent.ps1 -Prompt "your question"
echo.
echo Press any key to exit...
pause >nul
